name: 02 - Add Operation Column & Index

on:
  workflow_dispatch

jobs:

  add-operation-column-and-index:
    name: "Add operation - click here"
    runs-on: ubuntu-latest
        
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Add operation - if asked, please click on displayed link to authenticate
        timeout-minutes: 3
        env:
          PLANETSCALE_SERVICE_TOKEN_NAME: ${{secrets.PLANETSCALE_SERVICE_TOKEN_NAME}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          ORG_NAME: ${{secrets.ORG_NAME}}
          GITHUB_USER: ${{github.actor}}
        run: ./add-operation-column-and-index.sh
      - name: Please check out deployment request and branch connection string from step above
        run: |
          echo "Please check out deployment request and branch connection stringfrom step above."
          sleep 10
